std = "lua51"
max_line_length = false -- StyLua owns formatting
ignore = { "212/self", "611", "612", "613", "614", "621" } -- implicit self (house ns: methods) + whitespace — StyLua owns the latter
exclude_files = { "Includes/", ".claude/" } -- vendored or session-local, never linted
read_globals = {
	-- Libraries
	"LibStub",
	-- Frames & UI globals
	"ChatFrame1",
	"ChatFrameUtil",
	"CreateFont",
	"CreateFrame",
	"GameTooltip",
	"GameTooltipTextLeft1",
	"Minimap",
	"MinimapZoomIn",
	"MinimapZoomOut",
	"MiniMapTracking",
	"MiniMapTrackingButton",
	"MiniMapTrackingIcon",
	"SettingsPanel",
	"UIPanelWindows",
	"UIParent",
	"WorldFrame",
	-- Modern API namespaces
	"C_AddOns",
	"C_EventUtils",
	"C_Item",
	"C_Map",
	"C_Minimap",
	"C_QuestLog",
	"C_Seasons",
	"C_Secrets",
	"C_Spell",
	"C_Timer",
	"C_TooltipInfo",
	"C_UnitAuras",
	"Enum",
	"Settings",
	-- Legacy halves of compatibility guards
	"CancelTrackingBuff",
	"GetTrackingTexture",
	-- WoW API
	"CastSpellByID",
	"GAMEMENU_OPTIONS",
	"GetBindingKey",
	"GetBindingText",
	"KEY_BINDINGS",
	"KeyBindingFrame",
	"KeyBindingFrame_LoadUI",
	"NOT_BOUND",
	"SETTINGS_KEYBINDINGS_LABEL",
	"ShowUIPanel",
	"GetBuildInfo",
	"GetCVar",
	"GetCursorInfo",
	"GetGameMessageInfo",
	"GetInstanceInfo",
	"GetInventoryItemID",
	"GetLocale",
	"GetPhysicalScreenSize",
	"GetTime",
	"GetUnitSpeed",
	"InCombatLockdown",
	"INVSLOT_MAINHAND",
	"IsInInstance",
	"IsMounted",
	"IsPlayerSpell",
	"IsResting",
	"IsShiftKeyDown",
	"IsSpellKnown",
	"IsStealthed",
	"LOCALIZED_CLASS_NAMES_MALE",
	"SetCVar",
	"UnitAffectingCombat",
	"UnitCanAttack",
	"UnitCastingInfo",
	"UnitChannelInfo",
	"UnitClass",
	"UnitCreatureType",
	"UnitExists",
	"UnitIsDead",
	"UnitIsDeadOrGhost",
	"UnitIsPlayer",
	"UnitLevel",
	"UnitOnTaxi",
}
globals = {
	-- exactly the add-on's own sanctioned globals
	"TrackingEyeDB",
	"SLASH_TRACKINGEYE1",
	"SlashCmdList",
	"TrackingEye_CycleFarmAbility",
	"BINDING_NAME_TRACKINGEYE_CYCLE_FARM_ABILITY",
}
